"""Migration for model ApiLogs

Revision ID: 5dd07ae9b4b9
Revises: a9f3e8a0776f
Create Date: 2025-07-21 22:34:27.375780

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = "5dd07ae9b4b9"
down_revision = 'a9f3e8a0776f'
branch_labels = None
depends_on = None


def upgrade():
    """Apply migration changes.

    Add or modify database structures here.

    Example:
    op.add_column("users", sa.Column("new_column", sa.String(length=255), nullable=True))
    op.create_index("ix_users_new_column", "users", ["new_column"])
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_logs', sa.Column('auth_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    """Rollback migration changes.

    Undo changes made in upgrade().

    Example:
    op.drop_index("ix_users_new_column", table_name="users")
    op.drop_column("users", "new_column")
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_logs', 'auth_status')
    # ### end Alembic commands ###
