"""Migration for model ApiLogs

Revision ID: 6a070a3f0028
Revises: 5dd07ae9b4b9
Create Date: 2025-07-21 22:41:42.721780

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = "6a070a3f0028"
down_revision = '5dd07ae9b4b9'
branch_labels = None
depends_on = None


def upgrade():
    """Apply migration changes.

    Add or modify database structures here.

    Example:
    op.add_column("users", sa.Column("new_column", sa.String(length=255), nullable=True))
    op.create_index("ix_users_new_column", "users", ["new_column"])
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_logs', 'auth_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('api_logs', 'api_key_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('api_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    """Rollback migration changes.

    Undo changes made in upgrade().

    Example:
    op.drop_index("ix_users_new_column", table_name="users")
    op.drop_column("users", "new_column")
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('api_logs', 'api_key_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('api_logs', 'auth_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
