"""Migration for model ApiLogs

Revision ID: a9f3e8a0776f
Revises: 0bddfede6f33
Create Date: 2025-07-21 21:19:19.308598

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = "a9f3e8a0776f"
down_revision = '0bddfede6f33'
branch_labels = None
depends_on = None


def upgrade():
    """Apply migration changes.

    Add or modify database structures here.

    Example:
    op.add_column("users", sa.Column("new_column", sa.String(length=255), nullable=True))
    op.create_index("ix_users_new_column", "users", ["new_column"])
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('response_time', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('api_keys_user_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    """Rollback migration changes.

    Undo changes made in upgrade().

    Example:
    op.drop_index("ix_users_new_column", table_name="users")
    op.drop_column("users", "new_column")
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('api_keys_user_id_fkey'), 'api_keys', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
